# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [2]:
# Create a 1-dimensional NumPy array using np.array()
array1 = np.array([1, 2, 3])

# Create a 2-dimensional NumPy array using np.array()
array2 = np.array([[1, 2, 3],
                 [1, 4, 5]])

# Create a 3-dimensional Numpy array using np.array()
array3 = np.array([[[1, 2, 3],
                    [5, 6, 7],
                    [8, 9, 4]]])

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [9]:
array1

array([1, 2, 3])

In [5]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
array1, array1.shape, array1.ndim, array1.dtype, array1.size, type(array1)

(array([1, 2, 3]), (3,), 1, dtype('int32'), 3, numpy.ndarray)

In [7]:
array2

array([[1, 2, 3],
       [1, 4, 5]])

In [8]:
# Attributes of 2-dimensional array
array2.shape, array2.ndim, array2.dtype, array2.size, type(array2)

((2, 3), 2, dtype('int32'), 6, numpy.ndarray)

In [10]:
# Attributes of 3-dimensional array
array3.shape, array3.ndim, array3.dtype, array3.size, type(array3)

((1, 3, 3), 3, dtype('int32'), 9, numpy.ndarray)

In [153]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd
df = pd.DataFrame(array2)
df

0  1  2
0  1  2  3
1  1  4  5

In [18]:
# Create an array of shape (10, 2) with only ones
ones = np.ones((10, 2))
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [20]:
# Create an array of shape (7, 2, 3) of only zeros
zeros = np.zeros((7, 2, 3))
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [27]:
# Create an array within a range of 0 and 100 with step 3
array_ranged = np.arange(0, 100, 3)
array_ranged

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [32]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
array_random1 = np.random.randint(0, 10, size=(7,2))
array_random1

array([[8, 3],
       [9, 2],
       [5, 5],
       [1, 7],
       [5, 3],
       [4, 0],
       [2, 3]])

In [31]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
array_random2 = np.random.random(size=(3, 5))
array_random2

array([[0.30264651, 0.97147637, 0.98032089, 0.68085352, 0.43658764],
       [0.6992862 , 0.95363383, 0.88804826, 0.15982374, 0.90349791],
       [0.68811759, 0.19542177, 0.48143148, 0.98502785, 0.00972451]])

In [36]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
array_random3 = np.random.randint(0, 10, (4, 6))
array_random3

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [55]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
np.random.seed(44)
array_random4 = np.random.randint(1, 10, size=(3, 7))

# Find the unique numbers in the array you just created
np.unique(array_random4), array_random4

(array([1, 2, 4, 5, 6, 7, 8, 9]),
 array([[5, 4, 2, 4, 1, 5, 4],
        [9, 8, 8, 7, 4, 8, 4],
        [4, 7, 6, 5, 6, 2, 9]]))

In [154]:
# Find the 0'th index of the latest array you created
array_random4[0]

array([5, 4, 2, 4, 1, 5, 4])

In [62]:
# Get the first 2 rows of latest array you created
array_random4[:2]

array([[5, 4, 2, 4, 1, 5, 4],
       [9, 8, 8, 7, 4, 8, 4]])

In [71]:
# Get the first 2 values of the first 2 rows of the latest array
array_random4[:2, :2]

array([[5, 4],
       [9, 8]])

In [78]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
random_array5 = np.random.randint(0, 10, size=(3, 5))
ones = np.ones((3, 5))
random_array5, ones

(array([[4, 2, 8, 8, 4],
        [2, 4, 8, 2, 1],
        [9, 4, 6, 9, 3]]),
 array([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]))

In [79]:
# Add the two arrays together
array_together = random_array5 + ones
array_together

array([[ 5.,  3.,  9.,  9.,  5.],
       [ 3.,  5.,  9.,  3.,  2.],
       [10.,  5.,  7., 10.,  4.]])

In [77]:
# Create another array of ones of shape (5, 3)
random_array6 = np.random.randint(0, 10, size=(5, 3))
random_array5

array([[6, 7, 5],
       [5, 6, 2],
       [5, 1, 8],
       [9, 1, 8],
       [0, 9, 3]])

In [82]:
# Try add the array of ones and the other most recent array together
random_array5 + random_array6.T

array([[ 9,  2, 12, 15,  6],
       [11, 12, 10,  8,  6],
       [14,  4, 15, 15,  3]])

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

Answer: Transposte the matriz

In [84]:
# Create another array of ones of shape (3, 5)
another_array = np.ones((3, 5))

In [86]:
# Subtract the new array of ones from the other most recent array
random_array6.T - another_array

array([[ 4., -1.,  3.,  6.,  1.],
       [ 8.,  7.,  1.,  5.,  4.],
       [ 4., -1.,  8.,  5., -1.]])

In [87]:
# Multiply the ones array with the latest array
random_array6.T * another_array

array([[5., 0., 4., 7., 2.],
       [9., 8., 2., 6., 5.],
       [5., 0., 9., 6., 0.]])

In [88]:
# Take the latest array to the power of 2 using '**'
random_array6 ** 2

array([[25, 81, 25],
       [ 0, 64,  0],
       [16,  4, 81],
       [49, 36, 36],
       [ 4, 25,  0]])

In [90]:
# Do the same thing with np.square()
np.square(random_array6)

array([[25, 81, 25],
       [ 0, 64,  0],
       [16,  4, 81],
       [49, 36, 36],
       [ 4, 25,  0]])

In [91]:
# Find the mean of the latest array using np.mean()
np.mean(random_array6)

4.533333333333333

In [92]:
# Find the maximum of the latest array using np.max()
np.max(random_array6)

9

In [93]:
# Find the minimum of the latest array using np.min()
np.min(random_array6)

0

In [94]:
# Find the standard deviation of the latest array
np.std(random_array6)

3.0302181806302695

In [96]:
# Find the variance of the latest array
np.var(random_array6)

9.18222222222222

In [102]:
random_array6

array([[5, 9, 5],
       [0, 8, 0],
       [4, 2, 9],
       [7, 6, 6],
       [2, 5, 0]])

In [101]:
# Reshape the latest array to (3, 5, 1)
reshape6 = random_array6.reshape((3, 5, 1))
reshape6

array([[[5],
        [9],
        [5],
        [0],
        [8]],

       [[0],
        [4],
        [2],
        [9],
        [7]],

       [[6],
        [6],
        [2],
        [5],
        [0]]])

In [100]:
# Transpose the latest array
reshape6.T

array([[[5, 0, 6],
        [9, 4, 6],
        [5, 2, 2],
        [0, 9, 5],
        [8, 7, 0]]])

What does the transpose do?
Answer: Change the position of line numbers to columns

In [103]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
array_random7 = np.random.randint(0, 10, size=(3, 3))
array_random8 = np.random.randint(0, 10, size=(3, 2))

In [104]:
# Perform a dot product on the two newest arrays you created
np.dot(array_random7, array_random8)

array([[ 83,  73],
       [ 80,  34],
       [118, 102]])

In [105]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
array_random9 = np.random.randint(0, 10, size=(4, 3))
array_random10 = np.random.randint(0, 10, size=(4, 3))

In [106]:
# Perform a dot product on the two newest arrays you created
np.dot(array_random9, array_random10)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

It doesn't work. How would you fix it?

In [107]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
np.dot(array_random9.T, array_random10)

array([[ 83,  53,  70],
       [ 76,  41,  50],
       [115, 100,  78]])

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [111]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
array_random11 = np.random.randint(0, 10, size=(3, 3))
array_random12 = np.random.randint(0, 10, size=(3, 3))
array_random11, array_random12

(array([[1, 2, 0],
        [6, 4, 5],
        [2, 1, 2]]),
 array([[1, 2, 4],
        [0, 8, 2],
        [1, 8, 7]]))

In [110]:
# Compare the two arrays with '>'
array_random11 > array_random12

array([[ True, False,  True],
       [False, False, False],
       [False,  True,  True]])

What happens when you compare the arrays with `>`?

In [112]:
# Compare the two arrays with '>='
array_random11 >= array_random12

array([[ True,  True, False],
       [ True, False,  True],
       [ True, False, False]])

In [113]:
# Find which elements of the first array are greater than 7
array_random11 > 7

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [114]:
# Which parts of each array are equal? (try using '==')
array_random11 == array_random12

array([[ True,  True, False],
       [False, False, False],
       [False, False, False]])

In [116]:
array_random11

array([[1, 2, 0],
       [6, 4, 5],
       [2, 1, 2]])

In [115]:
# Sort one of the arrays you just created in ascending order
np.sort(array_random11)

array([[0, 1, 2],
       [4, 5, 6],
       [1, 2, 2]])

In [117]:
# Sort the indexes of one of the arrays you just created
np.argsort(array_random11)

array([[2, 0, 1],
       [1, 2, 0],
       [1, 0, 2]], dtype=int64)

In [121]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(array_random11)

3

In [122]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(array_random11)

2

In [131]:
array_random11

array([[1, 2, 0],
       [6, 4, 5],
       [2, 1, 2]])

In [148]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
np.argmax(array_random11, axis=1)

array([1, 0, 0], dtype=int64)

In [149]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
np.argmin(array_random11, axis=0)

array([0, 2, 0], dtype=int64)

In [161]:
# Create an array of normally distributed random numbers
mat1 = np.random.rand(3, 5)
mat1

array([[0.45967944, 0.61538568, 0.12889974, 0.58947964, 0.55206107],
       [0.4871203 , 0.54942133, 0.97899027, 0.17111106, 0.52752674],
       [0.70630516, 0.538515  , 0.40557028, 0.75914677, 0.71260489]])

In [162]:
np.std(mat1)

0.20634373984469556

In [164]:
# Create an array with 10 evenly spaced numbers between 1 and 100
np.linspace(1, 100, 10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.